name: Kollect Monitor

on:
  schedule:
    # Runs every 5 minutes from 6:00 AM IST to 12:00 AM IST
    # (Matches 12:30 AM UTC to 6:30 PM UTC)
    - cron: '30/5 0-17 * * *'
    - cron: '0-30/5 18 * * *'
  workflow_dispatch: # Allows you to click "Run" manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TARGET_CHAT: ${{ secrets.TARGET_CHAT }}
          MY_HANDLE: ${{ secrets.MY_HANDLE }}
        run: python scraper.py

      - name: Save Inventory (Commit and Push)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add inventory.json || exit 0
          git commit -m "Update inventory [skip ci]" || exit 0
          git push
